Neo [Crew]
Morpheus [Crew]
Trinity [Crew]
Cypher [Crew Matrix]
Smith [label="Agent Smith"]
Architect [Matrix]
<Neo Morpheus> [Knows]
<Neo Trinity> [Loves]
<Morpheus Trinity> [Knows]
<Morpheus Cypher> [Knows]
<Cypher Smith> [Knows]
<Smith Architect> [CodedBy]
